[project]
name = "financial-control-system"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.2",
    "environs>=14.1.1",
    "fastapi>=0.115.12",
    "sqlmodel>=0.0.24",
]
